# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
       
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy:deploy-file -DgroupId=com.github.2115-27 -DartifactId=helloworld -Dpackaging=jar -DrepositoryId=sample-helloworld-ant -Durl=https://github.com/2115-27/ -Dfile=HelloWorld.jar -Dversion=1.0.0
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
